Implement `_` pattern (#148)
mica-lang/mica pull request #150
Opened 2023-10-22 16:21 UTC by grisenti

Closes #148.
Closes #151.

2023-10-22 19:14 UTC, liquidev requested changes
Thank you for the pull request! I'm glad to see you willing to contribute code to Mica.

There are some minor nitpicks as well as more major reservations I have regarding the implementation, please address them before we proceed with merging into `main`.

2023-10-22 19:14 UTC, liquidev commented on tests/language/tuple/destructuring/discard-element.test.mi
> +# Test that destructuring works even while discarding a tuple member
nitpick: Test descriptions should have a period at the end of the sentence.
```suggestion
# Test that destructuring works even while discarding a tuple member.
```

2023-10-22 19:14 UTC, liquidev commented on tests/language/variable/discard-declaration.test.mi
> +# Declare a discarded variable
nitpick: Test descriptions should have a period at the end of the sentence.
```suggestion
# Declare a discarded variable.
```

2023-10-22 19:14 UTC, liquidev commented on src/ll/parser.rs
> +            },
todo: Use the `parse_unit` function instead of building the node manually here:
```suggestion
            TokenKind::Underscore => Ok(self.parse_unit(token, NodeKind::DiscardPattern)),
```

2023-10-22 19:14 UTC, liquidev commented on src/ll/codegen/tuples.rs
> +        fn destructure_member(generator: &mut CodeGenerator, ast: &Ast, key: NodeId, value: NodeId) -> Result<(), LanguageError> {
todo: This line is longer than 100 characters; please run `cargo fmt` to reformat all code before it's committed.

Sorry that this is not part of CI, I just haven't thought of it before because I have formatting on save enabled :sweat_smile:

2023-10-22 19:14 UTC, liquidev commented on src/ll/codegen/assignment.rs
> +                    }
(see my previous suggestion on special-casing `_` in records, I'm leaving this comment here so that you don't forget to update this case, too)

2023-10-22 20:13 UTC, grisenti commented on src/ll/codegen/tuples.rs
> +            }
I tried this initially but it would panic with this type of code:
```
let _ = 1
```
since it doesn't leave anything on the stack for the vm to return

2023-10-22 20:40 UTC, grisenti commented on src/ll/ast.rs
> +    DiscardPattern,
I think its better to keep the two separate, just to separate tokens from ast nodes. On the other hand, I doubt a different token will ever be used for this, so I'm fine with both.

2023-10-22 20:48 UTC, grisenti commented on tests/language/tuple/destructuring/discard-element.test.mi
> +assert(c == 3)
I think destructuring for records is broken. I get these results:
```
> let {x, y} = {x: 1, y: 2}
< { x: 1, y: 2 }

> x
< 2

> y
< 1
```
maybe members should be reversed [here](https://github.com/mica-lang/mica/blob/260ce8958a628a1a088128414fe9b251c3ff10d6/src/ll/codegen/tuples.rs#L132C11-L132C11) and [here](https://github.com/mica-lang/mica/blob/260ce8958a628a1a088128414fe9b251c3ff10d6/src/ll/codegen/tuples.rs#L97C14-L97C14).

2023-10-23 17:51 UTC, liquidev commented on tests/language/tuple/destructuring/discard-element.test.mi
> +assert(c == 3)
Oh, huh... It seems like I never included any `assert`ions in the test, only a `let` expression to test that the VM doesn't crash. Not good...

I'd be very glad if you could do a drive-by fix in this PR, but no pressure; I'll open an issue about this so it can be tracked separately in case you don't have time for it.

2023-10-23 17:59 UTC, liquidev commented on src/ll/ast.rs
> +    DiscardPattern,
My reasoning was:
- The existing single-token "unit" `TokenKind::Nil` can only result in a `NodeKind::Nil` expression, likewise with `True`, `False`
- Mica's only syntax is the expression syntax, so there is no risk of collision with other things. 
  - Only having an expression syntax is a design principle driving syntax decisions, so there will be no other uses for `_` I'm afraid
  - Pattern matching reuses expression syntax, therefore there is no such thing as a "pattern" syntactically
- Hence why the `_` token will ever only be valid in expressions - there is nowhere else we could use it.

As for separation, you already have the namespacing `TokenKind::*` vs `NodeKind::*`, which is enough in my opinion.

2023-10-23 18:04 UTC, liquidev commented on src/ll/codegen/tuples.rs
> +            }
I'd be interested in seeing what you've tried so far; as I've mentioned, it's important to respect the `result` parameter, so you should only be emitting a `Discard` only if `result == Expression::Discarded`:
```rs
if result == Expression::Discarded {
    generator.chunk.emit(Opcode::Discard);
}
```
`result` is `Expression::Used` for the last expression in a block, so it *should* not emit a `Discard` opcode in the case you've mentioned. If it does, I'd say that's probably a bug.

2023-10-23 20:25 UTC, grisenti commented on tests/language/tuple/destructuring/discard-element.test.mi
> +assert(c == 3)
Sure, should be fixed now. I also added a couple of tests for non-exhaustive destructuring

2023-10-28 07:11 UTC, grisenti commented on tests/language/tuple/destructuring/discard-element.test.mi
> +assert(c == 3)
I was adding some tests and found that:
```mica
let {y, x} = {y: 1, x: 2} 
```
fails with "error: type mismatch, expected Record{y, x} but got Record{x, y}"

2023-10-30 18:48 UTC, liquidev commented on tests/language/tuple/destructuring/discard-element.test.mi
> +assert(c == 3)
Let's get that fixed in another PR so as not to clutter this one. #152

2023-10-30 18:49 UTC, liquidev commented on src/ll/codegen/tuples.rs
> +            }
I'll look into simplifying the special cases later, for now thanks for the initial implementation :heart:

2023-10-30 19:00 UTC, liquidev commented
Alright, time to get this merged! Thank you once again for taking your time to contribute. I don't want to hold your contribution back so I'll clean up my remaining concerns on my own before 0.8.0 is released. Many thanks for doing some proper testing on records, it makes me a lot more confident it'll be a feature you can rely on.

2023-10-30 19:00 UTC, liquidev approved these changes

2023-10-30 19:01 UTC, merged